export const deckELI5: Record<string, string> = {
  "squirreled-away": "Build an adorable army of squirrels and overwhelm your opponents with cuteness (and numbers). Make treasure, sacrifice creatures for value, and watch your fuzzy friends take over the battlefield.",
  "graveyard-overdrive": "Turn your graveyard into a treasure chest! Bring creatures back from the dead and use them over and over. It's like having a zombie apocalypse you control.",
  "tricky-terrain": "Make your lands do wild things! This deck turns boring lands into exciting threats that damage opponents. Watch as the ground itself fights back.",
  "creative-energy": "Build amazing things with energy! Collect energy counters like currency, then spend them on powerful effects. It's like having a magical battery that powers your victory.",
  "quick-draw": "Be the fastest at the table! Play extra spells on other people's turns and always have an answer ready. You'll feel like a card-slinging cowboy.",
  "desert-bloom": "Turn the desert into a garden of death! Make your lands matter while draining your opponents' life. Nature has never been this dangerous.",
  "grand-larceny": "Steal everything! Take your opponents' best stuff and use it against them. You'll feel like a master thief pulling off the perfect heist.",
  "most-wanted": "Play as the bad guys! This outlaw-themed deck lets you break the rules and cause chaos. Crime pays in Commander!",
  "scrappy-survivors": "Survive the wasteland with grit and determination! Build up from nothing and overwhelm with scrappy survivors. Every setback makes you stronger.",
  "science": "Harness the power of science! Generate energy counters with artifacts, then spend them on powerful effects. It's like a wasteland laboratory of possibilities.",
  "hail-caesar": "Build a Roman empire in the wasteland! Lead armies of soldiers to victory. All roads lead to your domination.",
  "mutant-menace": "Unleash radioactive mutants! Create powerful creatures and pump them up. Radiation has never been this fun.",
  "blame-game": "Play detective and solve mysteries! Investigate clues and draw tons of cards. You'll feel like Sherlock Holmes with magic spells.",
  "revenant-recon": "Bring back the dead to solve crimes! Your graveyard is full of witnesses ready to testify. Death is just the beginning.",
  "deadly-disguise": "Nothing is what it seems! Hide creatures face-down and reveal them at the perfect moment. Keep your opponents guessing.",
  "deep-clue-sea": "Dive deep for treasure and clues! This deck rewards you for investigating with powerful card draw. The deeper you go, the more you find.",
  "veloci-ramp-tor": "Clever girl! Create dinosaur tokens and ramp up fast. Life finds a way… to win the game!",
  "timey-wimey": "Travel through time and space! Take extra turns and rewrite history. Wibbly wobbly, timey wimey fun.",
  "blast-from-the-past": "Revisit the past and use it to your advantage! Suspend cards and bring them back at the perfect time. The past is never really gone.",
  "paradox-power": "Break the laws of time! Create paradoxes and benefit from the chaos. Who says time has to make sense?",
  "masters-of-evil": "Play as the Doctor's greatest enemies! Villains have never been this fun. Exterminate!",
  "chaos-incarnate": "Embrace chaos! Random effects and wild swings make every game unpredictable. In the grim darkness of the far future, there is only chaos.",
  "tyranid-swarm": "Consume everything! Create endless alien creatures that devour all in their path. The hive mind demands it.",
  "necron-dynasties": "Ancient robots rise again! Bring artifacts back from the dead. Death is merely a temporary inconvenience.",
  "forces-of-the-imperium": "For the Emperor! Lead humanity's finest warriors to victory. There is only war.",
  "ruinous-powers": "Make dark deals for power! Demons and sacrifices fuel your victory. The dark gods smile upon you.",
  "hosts-of-mordor": "Command the forces of darkness! Build armies of orcs and overwhelm the good guys. One deck to rule them all.",
  "riders-of-rohan": "Ride to victory! Fast, aggressive creatures charge into battle. A day may come when this deck fails, but it is not this day!",
  "food-and-fellowship": "Share a feast and make friends! This fun, friendly deck rewards you for playing nice. Second breakfast included.",
  "elven-council": "Elves unite! Elegant creatures work together for devastating combos. Immortal beauty meets deadly efficiency.",
  "collector-ouphe": "Break artifacts and punish your opponents! This deck hates artifacts and makes sure everyone knows it. Perfect for games where everyone else is playing robots.",
  "planar-genesis": "Create new worlds! Make land tokens and build an empire from scratch. You're basically a god of creation.",
  "uprising": "Lead a revolution! Create citizen tokens and rebel against tyranny. Power to the people!",
  "anikthea": "Enchant the world! Fill the battlefield with powerful enchantments that warp reality. Magic has never been this enchanting.",
  "zhulodok": "Cast colorless giants! This deck goes big with massive Eldrazi creatures. Size definitely matters here.",
  "party-time": "Adventure awaits! Build a balanced party of creatures and explore dungeons. It's D&D in Magic form!",
  "pantlaza": "Discover the unknown! Reveal cards and get powerful effects. Every turn is a treasure hunt in the lost caverns.",
  "cavern-critters": "Cute underground creatures unite! Otters, moles, and other adorable animals team up. Cuteness overload in the best way!",
  "explorers-of-the-deep": "Dive into the depths! Explore underwater ruins and discover lost treasures. The deep sea hides amazing secrets.",
  "ahoy-mateys": "Pirates! Sail the high seas, steal treasure, and fight with pirates. Yo ho ho and a bottle of mana!",
  "blood-rites": "Sacrifice for power! Use your creatures as fuel for devastating effects. Every death makes you stronger.",
  "miracle-worker": "Angels and miracles! Divine creatures protect you while you build toward victory. Heaven's army at your command.",
  "jump-scare": "Keep opponents guessing with mysterious face-down creatures! Ramp up your lands, draw tons of cards, and reveal surprises at the perfect moment.",
  "sliver-swarm": "Slivers unite! Every sliver makes all your slivers better. It's a hive mind of alien terror.",
  "rainbow-bridge": "All five colors! This deck does everything from artifacts to enchantments. Why choose one strategy when you can have them all?",
  "walking-dead": "Survive the zombie apocalypse! Create zombie tokens and sacrifice creatures for value. In this world, you're either the walking dead or soon to be.",
  "stranger-things": "Enter the Upside Down! Flip between worlds and creatures in this creepy, mysterious deck. Things are about to get strange.",
  "transformers": "Robots in disguise! Convert vehicles into powerful robots and roll out to victory. More than meets the eye!",
  "street-fighter": "Hadouken! Build up combat power and unleash devastating attacks. Every hit counts in this fighting game tribute!",
  "fortnite": "Battle royale! Aggressive creatures and surprise attacks secure the victory. Last one standing wins!",
  "godzilla": "Kaiju rampage! Massive monsters destroy everything in their path. Let them fight!",
  "final-fantasy": "Summon legendary warriors and monsters! Epic battles with iconic characters from the games. Time to limit break your opponents!",
  "monty-python": "Run away! This silly, chaotic deck captures the absurdist humor of Monty Python. Nobody expects this deck!",
  "princess-bride": "As you wish! A fairytale adventure with romance, sword fights, and giants. Inconceivable!",
  "breed-lethality": "Spread corruption and grow stronger! This deck uses counters on everything to snowball into an unstoppable force. Every turn makes you more powerful.",
  "invent-superiority": "Build a robot army! Artifacts and tokens combine for explosive combos. Welcome to the machine age.",
  "open-hostility": "Attack relentlessly! This aggressive deck punishes opponents with non-stop combat. No mercy, just beatdown.",
  "stalwart-unity": "Grow your army! Create lots of creature tokens and watch them become massive threats. Strength in numbers!",
  "entropic-uprising": "Embrace randomness! Chaotic effects and wild swings make every game different. You never know what'll happen next!",
  "draconic-domination": "Command dragons! This five-color deck lets you play with the most iconic creatures in Magic. Unleash fire and fury!",
  "vampiric-bloodlust": "Vampire tribal! Drain life and build an army of bloodsuckers. The night belongs to you!",
  "arcane-wizardry": "Wizard tribal! Spells and wizards work together. Knowledge is power!",
  "feline-ferocity": "Equipment cats! Gear up your feline friends and attack. Cats with swords!",
  "plunder-the-graves": "Graveyard recursion! Bring creatures back over and over. Death is just a speed bump!",
  "seize-control": "Steal and copy! Take opponents' stuff and use it better. Why build when you can borrow?",
  "swell-the-host": "Small creatures get huge! Build up tiny creatures into giants. David beats Goliath!",
  "wade-into-battle": "Giants! Big creatures, big damage. Sometimes simple is best!",
  "call-the-spirits": "Enchantments and spirits! Enchant the world and create ghosts. Hauntingly beautiful!",
  "forged-in-stone": "Equipment tribal! Every creature becomes a warrior with the right gear. Suit up and fight!",
  "peer-through-time": "Time control! Take extra turns and see the future. You control time itself!",
  "built-from-scratch": "Artifact value! Weld artifacts together for incredible combos. Tinker time!",
  "guided-by-nature": "Elf ramp! Make tons of mana and cast huge spells. Nature provides!",
  "sworn-to-darkness": "Demon deals! Make pacts with demons for power. The price is worth it!",
  "eternal-bargain": "Life gain control! Gain life, draw cards, outlast everyone. Slow and steady!",
  "evasive-maneuvers": "Political flying! Make deals and avoid damage. Diplomacy wins wars!",
  "mind-seize": "Spell theft! Cast opponents' spells. Why build a deck when you can play theirs?",
  "power-hungry": "Tokens and sacrifice! Create creatures, then sacrifice them for value. Hungry for victory!",
  "nature-of-the-beast": "Tokens everywhere! Create creature tokens and overwhelm with numbers. An unstoppable swarm!",
  "heavenly-inferno": "Angels, demons, dragons! This deck has all the coolest creature types. Maximum epic!",
  "mirror-mastery": "Copy everything! Spells, creatures, everything gets doubled. More is always better!",
  "counterpunch": "Token counters! Create tokens and make them huge. An army of giants!",
  "political-puppets": "Group hug manipulation! Give things away for your own benefit. Trojan horse strategy!",
  "devour-for-power": "Mill and steal! Fill graveyards and steal the best creatures. Feast on everyone's power!",
  "warhammer-chaos": "Chaos Space Marines! Corrupt everything with the ruinous powers. For Chaos!",
  "warhammer-necrons": "Ancient death robots awaken! Recursive threats that won't stay dead. The Necrons never truly die.",
  "warhammer-tyranids": "The swarm consumes all! Create endless alien bugs that devour everything. Resistance is futile.",
  "warhammer-imperium": "Humanity's last stand! Lead the Imperial Guard to glorious victory. The Emperor protects!",
  "animated-army": "Enchantments become creatures! Your enchantments come to life and attack. Everything is alive!",
  "peace-offering": "Group hug! Help everyone… but help yourself more. Everybody wins (except they don't).",
  "family-matters": "Human tribal! Build a family of humans working together. Humans are stronger together.",
  "eldrazi-incursion": "Colorless monsters! Massive Eldrazi aliens warp reality. These things shouldn't exist, but they do.",
  "death-toll": "Drain life relentlessly! Every action slowly kills your opponents. Death by a thousand cuts.",
  "endless-punishment": "Punish your opponents for every move they make while draining their life away. The more they play, the stronger you get!",
  "ommodore-guff": "Spell-slinging madness! Cast lots of spells and draw tons of cards. It's a magic missile extravaganza!",
  "undead-unleashed": "Zombie apocalypse! Build an army of the undead and overwhelm your opponents. Brains… and victory!",
  "primal-genesis": "Make tons of creatures! Populate and create token copies of your best creatures. Multiply and conquer!",
  "timeless-wisdom": "Cycle cards for value! Draw through your deck while building up powerful effects. Every card cycles toward victory!",
  "enhanced-evolution": "Mutate creatures into super-monsters! Stack creatures on top of each other for incredible abilities. Evolution never looked so good!",
  "arcane-maelstrom": "Cascade into chaos! Every spell you cast lets you cast another free spell. It's an avalanche of magic!",
  "symbiotic-swarm": "Keywords matter! Build creatures with lots of abilities like flying, deathtouch, and lifelink. Every keyword makes you stronger!",
  "ruthless-regiment": "Humans with death touches! Build an army of skilled warriors. Every creature is a threat!",
  "mystic-intellect": "Flashback spells! Cast spells from your graveyard for double value. Why cast a spell once when you can cast it twice?",
  "primal-hunger": "Grow huge creatures! This deck makes everything bigger and scarier. Size absolutely matters!",
  "subjective-reality": "Morph creatures! Flip creatures face-up for surprise effects. Nothing is what it seems!",
  "merciless-rage": "Madness! Discard cards for value and go aggressive. Sometimes losing your mind is a good strategy!",
  "faceless-menace": "Manifest creatures! Play creatures face-down and reveal them later. Mystery and power combined!",
  "exotic-orchard": "Five-color mana! Play all the colors and all the best spells. Why limit yourself?",
  "draconic-dissent": "Rebel dragons! Dragons that challenge authority. Burn everything in dragonfire!",
  "phantom-premonition": "Spirits and spirits! Ghostly creatures haunt your opponents. Boo!",
  "aura-of-courage": "Enchant creatures! Pump up your creatures with powerful auras. Every creature becomes a champion!",
  "sneak-attack": "Ninjas and rogues! Slip past defenses and deal massive damage. Silent but deadly!",
  "land-wrath": "Lands that fight! Your lands become creatures and attack. Even the ground is against them!",
  "counter-surge": "Counters on everything! Build up +1/+1 counters and proliferate them. Every turn makes you stronger!",
  "empyrial-storm": "Spells matter! Cast lots of instants and sorceries. It's raining magic!",
  "wild-fury": "Werewolves! Transform creatures from humans to wolves. When the moon rises, you win!",
  "deadly-venom": "Snakes with deathtouch! Poisonous creatures kill anything they touch. One bite is fatal!",
  "power-and-profit": "Treasures everywhere! Make treasure tokens and use them for powerful effects. Get rich and win!",
  "silverquill-statement": "Words have power! Use spells and politics to control the game. The pen is mightier!",
  "prismari-performance": "Art is magic! Spellslinging and big finishers. Every turn is a masterpiece!",
  "witherbloom-witchcraft": "Life drain! Gain life while opponents lose it. Every point of life is a resource!",
  "lorehold-legacies": "History comes alive! Bring back legendary creatures from your graveyard. The past isn't done yet!",
  "quandrix-quantification": "Math is magic! Copy spells and double effects. Two plus two equals you win!",
  "spirit-squadron": "Flying spirits! Evasive creatures that opponents can't block. Death from above!",
  "dragonic-domination": "Five-color dragons! Every color, every dragon, maximum awesome. Burn it all!",
  "arm-for-battle": "Equipment strategy! Suit up your creatures with powerful gear and attack. Every creature becomes a champion!",
  "buckle-up": "Vehicles matter! Pilot vehicles into combat and ram your opponents. Driving to victory!",
  "reap-the-tides": "Big sea creatures! Ramp hard and play massive threats from the deep. The ocean is on your side!",
  "elven-empire": "Elf tribal tokens! Create tons of elf tokens and overwhelm. The forest army marches!",
  "coven-counters": "Witch coven! Build up creatures with different powers. United in diversity!",
  "dungeons-of-death": "Venture into dungeons! Explore dungeons for rewards. Every adventure makes you stronger!",
  "planar-portal": "Exile matters! Exile cards and benefit from it. Banishment is power!",
  "undead-unleashed-2021": "Zombie horde! Create endless zombies and attack. The dead walk!",
  "draconic-rage": "Dragon tribal with treasures! Make treasure, cast dragons, burn everything. Fire and gold!",
  "aura-storm": "Aura voltron! Enchant one creature and make it unstoppable. One champion to rule them all!",
  "quantum-quandary": "Science fiction! Manipulate time and space. Physics is optional!",
  "rebellion-rising": "Rebel alliance! Build an army of rebels and fight back. Resistance wins!",
  "adaptive-enchantment": "Enchantment tribal! Every enchantment makes you stronger. Magic reality!",
  "growth-surge": "Counter proliferation! Add counters to everything and watch them multiply. Exponential growth!",
  "rogues-gallery": "Rogue tribal! Sneak in, deal damage, steal cards. Thievery pays!",
  "eldrazi-unbound": "Colorless titans! Cast massive Eldrazi and warp reality. They shouldn't exist!",
  "lands-wrath-2": "Landfall! Every land you play triggers powerful effects. The ground itself attacks!",
  "party-legends": "Legendary creatures! Build a party of legends and adventure. Heroes unite!",
  "myr-matrix": "Myr tribal! Robot myr creatures swarm the battlefield. Beep boop, you lose!",
  "tezzeret-control": "Artifact control! Control the game with artifacts. Machines rule!",
  "boros-battalion": "Soldiers attack! Military precision and aggressive combat. March to victory!",
  "simic-evolve": "Evolve creatures! Creatures get better when bigger creatures arrive. Evolution in action!",
  "rakdos-carnival": "Pain and pleasure! Fast, aggressive demons and devils. Join the show!",
  "izzet-spellslinger": "Spells and experiments! Cast lots of spells and profit. Science!"
};
