export const deckELI5: Record<string, string> = {
  "walking-dead-1": "Survive the zombie apocalypse with The Walking Dead! Build a ruthless deck featuring Negan and other survivors. Sacrifice creatures, create treasure, and outlast your opponents in this dark, post-apocalyptic showdown.",
  "transformers-autobots": "Robots in disguise! Bring Transformers to your game with Optimus Prime leading an army of vehicles and artifacts. Convert resources into powerful mechs and roll out to victory!",
  "transformers-decepticons": "Join the Decepticons! Megatron leads an army of evil robots in this artifact-heavy deck. Transform vehicles into warriors and crush the Autobots!",
  "timey-wimey": "Travel through time and space with Doctor Who! Manipulate the timeline, take extra turns, and outsmart your opponents with the Time Lord leading the way. Bigger on the inside than it looks!",
  "blast-from-the-past": "Adventure across time with Doctor Who! This deck features iconic characters and paradoxical mechanics. Suspend spells, bend time, and create timey-wimey chaos!",
  "doctor-who-paradox": "Harness temporal paradoxes with Doctor Who! Copy spells, manipulate the stack, and create mind-bending combos. For players who love clever, complex plays!",
  "doctor-who-masters": "Join the dark side with Doctor Who's greatest villains! The Master, Daleks, and Cybermen unite in this evil deck. Control the board and dominate through schemes and destruction.",
  "tyranid-swarm": "Unleash the Tyranid swarm from Warhammer 40K! An endless horde of alien creatures devours everything in its path. Go wide with tokens and overwhelm your opponents with sheer numbers.",
  "necron-dynasties": "Command the immortal Necrons from Warhammer 40K! These ancient robot skeletons keep coming back from the dead. Build artifacts, recur creatures, and grind down your enemies.",
  "forces-of-the-imperium": "For the Emperor! Lead the Space Marines and Imperial forces from Warhammer 40K. Aggressive creatures and powerful equipment make this a straightforward combat deck.",
  "the-ruinous-powers": "Enter the grimdark future of Warhammer 40K! Chaos reigns in this deck full of demons and dark powers. Embrace the madness and corruption to dominate the battlefield.",
  "warhammer-orks": "WAAAGH! Lead a horde of Orks from Warhammer 40K! This aggressive green tide smashes everything with brute force. More dakka, more combat!",
  "science": "Harness the power of science in the Fallout wasteland! Generate energy with artifacts and gadgets, then spend it on devastating effects. It's like a post-apocalyptic laboratory!",
  "hail-caesar": "Ave! Lead Caesar's Legion from Fallout in brutal combat. This aggressive deck attacks relentlessly and rewards you for dealing damage. Victory through strength!",
  "mutant-menace": "Embrace the radiation! This Fallout deck is all about mutants and adaptation. Grow your creatures, manipulate +1/+1 counters, and evolve into unstoppable threats.",
  "scrappy-survivors": "Survive the wasteland in this Fallout-themed deck! Scavenge for resources, make tough choices, and adapt to the harsh post-nuclear world.",
  "hosts-of-mordor": "Serve the Dark Lord in this Lord of the Rings deck! Command orcs and the armies of Mordor. Sacrifice creatures and create tokens for overwhelming evil forces.",
  "riders-of-rohan": "Ride forth with the Riders of Rohan! This Lord of the Rings deck is all about mounted combat and aggressive attacks. For Rohan!",
  "food-and-fellowship": "Second breakfast! This cozy Lord of the Rings deck creates food tokens and builds a friendly board. Perfect for players who love hobbits and incremental advantage.",
  "elven-council": "Journey to Middle-earth with the Elves! This Lord of the Rings deck features magic, powerful synergies, and elegant gameplay.",
  "limit-break": "Enter the world of Final Fantasy! Unleash limit breaks and summon powerful allies. This deck features iconic characters and epic magic from the beloved RPG series!",
  "street-fighter-1": "Hadouken! Battle with Street Fighter characters in this combat-focused deck. Chain together attacks and special moves to KO your opponents!",
  "street-fighter-2": "Shoryuken! More Street Fighter action with iconic fighters and combos. Perfect your fighting game strategies on the battlefield!",
  "quick-draw": "Fast as lightning! This cowboy deck attacks aggressively with quick-draw mechanics. Draw first, ask questions later!",
  "jurassic-world-1": "Life finds a way! Bring Jurassic World to your game with rampaging dinosaurs. Create massive prehistoric creatures and stomp your opponents into extinction!",
  "dinosaur-empire": "Unleash prehistoric power with rampaging dinosaurs! These massive creatures get bigger and scarier as the game goes on. Stomp your opponents into the Stone Age!",
  "stranger-things-1": "Enter The Upside Down from Stranger Things! This eerie deck manipulates alternate realities and features iconic characters from Hawkins. Strange things are happening!",
  "princess-bride-1": "As you wish! The Princess Bride comes to Magic with adventure and romance. This deck is full of charm, clever plays, and happily-ever-after moments. Inconceivable!",
  "fortnite-1": "Drop into battle with Fortnite! Build resources, play aggressively, and be the last one standing. Victory Royale awaits!",
  "monty-python-1": "Bring the silly brilliance of Monty Python to your game! This quirky deck features absurd humor and unexpected strategies. 'Tis but a scratch!",
  "godzilla-1": "Unleash kaiju mayhem with Godzilla! Massive monsters battle for supremacy in this deck of destructive titans. Stomp your opponents into rubble!",
  "squirreled-away": "Build an adorable army of squirrels! Create tons of squirrel tokens and overwhelm opponents with cuteness (and numbers). Perfect for players who love cute creatures and going wide.",
  "family-matters": "A heartwarming tribal deck featuring adorable woodland creatures! Build a community of critters that support each other. Great for players who want wholesome fun.",
  "animated-army": "Bring your artifacts to life! This quirky deck turns everyday objects into creatures. Perfect for players who love creative strategies and surprising synergies.",
  "peace-offering": "Make friends… then win! This political deck helps everyone while quietly building your advantage. Perfect for players who love negotiation and deals.",
  "death-toll": "Welcome to the haunted house! This creepy deck drains life and creates terrifying creatures. Perfect for horror fans who want dark, atmospheric gameplay.",
  "endless-punishment": "Punish your opponents for every move they make while draining their life away! The more they play, the stronger you get. Sadistic and satisfying!",
  "jump-scare": "Keep your opponents guessing with mysterious face-down creatures! Ramp up your lands, draw tons of cards, and reveal surprises at the perfect moment.",
  "carnival-of-souls": "Step right up to the creepy carnival! This deck sacrifices creatures and drains life. Every attraction has a dark price!",
  "blame-game": "Solve the mystery while framing your opponents! This detective-themed deck creates clues and investigates. Perfect for players who love puzzle-solving gameplay.",
  "revenant-recon": "Investigate the crime scene! This deck creates clue tokens and rewards you for finding evidence. Great for players who want strategic, interactive gameplay.",
  "deadly-disguise": "Nothing is as it seems in this mystery deck! Disguise creatures, create illusions, and outwit your opponents with clever deception.",
  "deep-clue-sea": "Dive deep into investigation! This sea-themed mystery deck creates clues and draws cards. Perfect for players who love both sea creatures and detective work.",
  "grand-larceny": "Saddle up, partner! This wild west deck is all about stealing, treasure, and outlaw synergies. Rob your opponents blind!",
  "most-wanted": "Become the most notorious outlaw in the west! This aggressive deck rewards you for committing crimes and breaking the law. Yeehaw!",
  "desert-bloom": "Tame the wild frontier! This deck creates a desert oasis with lands and creatures that thrive in harsh conditions. Manifest your destiny!",
  "creative-energy": "Harness pure creative power! This spellslinger deck rewards you for casting instants and sorceries. Copy spells and unleash magical chaos!",
  "tricky-terrain": "The land itself becomes your weapon! This deck manipulates lands in surprising ways. Perfect for players who want unique strategies.",
  "graveyard-overdrive": "The graveyard is just extra storage! Fill it up and bring back your best creatures. Death is merely an inconvenience!",
  "eldrazi-incursion": "Summon cosmic horrors from beyond reality! Eldrazi are massive, reality-warping creatures that exile and destroy everything. Embrace the void!",
  "counter-intelligence": "Explore the cosmos with spacecraft and artifacts! This deck uses counters and proliferate to build overwhelming advantage. The future is now!",
  "world-shaper": "Shape entire worlds! This deck sacrifices lands to create massive effects. Destruction leads to creation in this explosive strategy!",
  "eternal-might": "Harness eternal power from across the multiverse! This deck builds unstoppable forces that transcend time and space.",
  "living-energy": "Pure energy given form! This deck manipulates energy counters and artifacts for explosive plays. Power unlimited!",
  "abzan-armor": "Build an impenetrable fortress! This defensive deck uses +1/+1 counters and protection. Slow, steady, and unstoppable!",
  "jeskai-striker": "Strike with precision and speed! This deck features flying creatures and combat tricks. Hit hard, dodge harder!",
  "mardu-surge": "Charge into battle with warriors! This aggressive deck rewards attacking and creates overwhelming combat pressure. Victory or death!",
  "temur-roar": "Unleash primal fury! This deck features ferocious creatures that grow massive. Raw power meets savage strategy!",
  "counter-blitz": "Blitz your opponents with fast creatures! This aggressive deck attacks early and often. Speed kills!",
  "revival-trance": "Bring creatures back from the dead! This reanimation deck puts huge threats into play early. Death is just the beginning!",
  "scions-and-spellcraft": "Create Eldrazi spawn and cast big spells! This deck ramps with tokens before unleashing massive sorceries. Growth leads to power!",
  "miracle-worker": "Miracles happen! This deck manipulates the top of your library for perfect draws and devastating reveals. Faith rewarded!",
  "party-time": "It's party time! Build a full adventuring party with clerics, rogues, warriors, and wizards. Perfect for D&D fans!",
  "ninja-strike": "Strike from the shadows! This ninja deck features unblockable creatures and surprise attacks. The enemy never sees it coming!",
  "moonfolk-ascension": "Soar with mystical moonfolk! This deck manipulates lands and creates flying armies. Rise above the conflict!",
  "rat-colony": "Unleash a swarm of rats! This deck creates endless rat tokens. Overwhelming numbers win the day!",
  "snake-basket": "Serpents strike! This deck features snakes and deathtouch creatures. One bite is all it takes!",
  "tinker-time": "Build amazing contraptions! This artifact deck creates value through clever engineering. Innovation wins!",
  "phyrexian-swarm": "All will be compleat! This Phyrexian deck corrupts and infects. Join the machine perfection!",
  "planeswalker-party": "Superfriends assemble! This deck features multiple planeswalkers working together. Ultimate abilities everywhere!",
  "sliver-swarm": "Slivers share abilities in creepy, awesome ways! Each sliver makes all your slivers stronger. Build a hivemind that evolves into an unstoppable swarm!",
  "aura-of-courage": "Enchant your creatures with divine power! This aura deck makes creatures huge. Devotion brings victory!",
  "draconic-rage": "Unleash dragon fury! This aggressive dragon deck burns and smashes. Fire from above!",
  "werewolf-pack": "The pack hunts at night! This werewolf deck transforms creatures for overwhelming attacks. Run with the wolves!",
  "bear-force-one": "Bears! This deck features adorable but deadly bears. Don't underestimate the fuzzy ones!",
  "shapeshifter-swarm": "Become anything! This shapeshifter deck adapts and copies. Ultimate flexibility!",
  "lorehold-legacies": "Bring history to life! This deck reanimates legendary creatures from the graveyard. The past is never truly dead!",
  "goblin-gang": "Goblins everywhere! This chaotic deck creates goblin tokens and causes mayhem. Quantity over quality!",
  "squirrel-mob": "More squirrels! This deck creates an army of adorable squirrels. They're cute until they're deadly!",
  "prosper-tome-bound": "Exile and profit! This deck plays cards from exile and generates treasure. Nothing truly leaves the game!",
  "spirit-squadron": "Ghostly spirits haunt the battlefield! This deck features ethereal flyers and graveyard tricks. The dead don't rest!",
  "atog-feast": "Feed the atogs! This deck sacrifices artifacts for huge creatures. Everything is fuel!",
  "undead-unleashed": "Zombies rise! This deck creates zombie tokens and brings creatures back. The graveyard is just the beginning!",
  "vampiric-bloodline": "Aristocratic vampires drain life! This deck features vampire synergies and lifegain. Elegant and deadly!",
  "arcane-maelstrom": "Cast spells for free! This chaotic deck cascades through your library. Every spell triggers more spells!",
  "elemental-fury": "Elementals embody raw nature! This deck summons powerful elemental forces. Primal power unleashed!",
  "ooze-experiment": "Oozes absorb everything! This deck creates ooze tokens that grow. Sticky and unstoppable!",
  "phoenix-rebirth": "Rise from the ashes! This deck features phoenixes that keep coming back. Resurrection is inevitable!",
  "skeleton-crew": "Skeletal pirates! This deck combines undead and treasure. Spooky sailors!",
  "cephalid-experiment": "Nautilus and octopi manipulate the sea! This deck mills and manipulates. The deep thinks!",
  "reap-the-tides": "Ride massive sea creatures! This deck ramps lands and creates oceanic leviathans. The ocean's power is unstoppable!",
  "ruthless-regiment": "Humans unite! This aggressive human tribal deck goes wide with tokens. Strength in numbers!",
  "symbiotic-swarm": "Insects with keywords! This deck creates token creatures with flying, deathtouch, and more. Swarm your opponents!",
  "hydra-growth": "Hydras grow huge! This deck creates X-cost creatures that get massive. Infinite potential!",
  "faceless-menace-2019": "Morph creatures hide their nature! Flip creatures face-up for surprises. Nothing is what it seems!",
  "merciless-rage": "Madness reigns! This deck discards cards for value and attacks aggressively. Embrace the chaos!",
  "mystic-intellect": "Flashback your spells! This deck plays cards from the graveyard repeatedly. The past becomes the future!",
  "primal-genesis": "Populate tokens endlessly! This deck creates and copies tokens. Build an unstoppable army!",
  "horse-parade": "Cavalry charge! This deck features horses and mounted warriors. Ride to victory!",
  "adaptive-enchantment": "Enchantments everywhere! This deck builds a web of ongoing effects. Magic saturates the board!",
  "exquisite-invention": "Build magnificent artifacts! This deck creates artifact tokens and generates endless value. Engineering excellence!",
  "natures-vengeance-2018": "Lands matter! This deck plays extra lands and turns them into weapons. The earth rises up!",
  "subjective-reality": "Reality bends! This deck manipulates the top of your library and creates illusions. Control destiny!",
  "fungus-forest": "Fungus grows! This deck creates saproling tokens and spreads spores. Decomposition and growth!",
  "myr-matrix": "Myr artifacts assemble! This deck creates myr tokens and artifact synergies. Robotic efficiency!",
  "fortress-defense": "Build an impenetrable fortress! This defensive deck protects and outlasts. Walls win wars!",
  "scarecrow-reaper": "Creepy scarecrows! This deck features artifact creatures with changeling. Everything is a scarecrow!",
  "insect-swarm": "Insects everywhere! This deck creates insect tokens and overwhelms. The hive marches!",
  "arcane-wizardry": "Master wizards! This deck features wizard tribal and spellslinging. Knowledge is power!",
  "draconic-domination": "Dragons of every color! This five-color deck lets you play the biggest dragons. Hoard treasure and rain fire!",
  "feline-ferocity": "Cats with equipment! Lead fierce felines with weapons and tribal synergies. Purrfect hunters!",
  "plunder-the-graves": "Sacrifice for value! This deck sacrifices creatures and brings them back. The cycle continues!",
  "vampiric-bloodlust": "Drain opponents dry! This vampire deck gains life while dealing damage. Blood magic!",
  "merfolk-seaside": "Merfolk swarm the seas! This aquatic tribal deck creates tokens and controls tides. The ocean's children!",
  "faerie-schemes": "Mischievous faeries! This tricky deck counters spells and steals permanents. Fairy tales aren't nice!",
  "kithkin-community": "Tiny but mighty! This kithkin tribal deck goes wide with small creatures. Community strength!",
  "treefolk-grove": "Ancient treefolk! This deck features defensive plant creatures. The forest protects!",
  "minotaur-herd": "Minotaurs charge! This aggressive tribal deck features horned warriors. The maze awaits!",
  "sphinx-wisdom": "Wise sphinxes! This deck features flying creatures and riddles. Knowledge brings victory!",
  "breed-lethality": "Grow creatures huge! This deck uses +1/+1 counters. Start small, end gigantic!",
  "entropic-uprising": "Chaos and randomness! This deck features unpredictable effects. Embrace entropy!",
  "invent-superiority": "Artifacts reign! This deck builds machines and generates value. Technology conquers!",
  "open-hostility": "Chaos and combat! Big creatures attack aggressively. Hit hard, hit fast!",
  "stalwart-unity": "Unite and protect! Create tokens and build defenses. Strength through cooperation!",
  "mirror-mastery": "Copy everything! This deck duplicates spells and creatures. Double the trouble!",
  "call-the-spirits": "Spirits from beyond! This ghostly deck features ethereal creatures. The dead walk!",
  "forged-in-stone": "Equipment matters! Gear up creatures with weapons and armor. Armed and dangerous!",
  "peer-through-time": "Manipulate time! This deck takes extra turns. Time is a weapon!",
  "built-from-scratch": "Artifacts assemble! This deck creates artifact creatures. Building the future!",
  "guided-by-nature": "Nature's wisdom! Ramp lands and create massive creatures. The forest provides!",
  "heavenly-host": "Angels protect! This deck features divine flying creatures. Justice from above!",
  "heavenly-inferno": "Angels and demons! This deck features divine and dark creatures. Heaven and hell unite!",
  "counterpunch": "Political tokens! Create creatures and make deals. Build alliances, then break them!",
  "political-puppets": "Control through politics! Make deals and manipulate the game. Everyone's a pawn!",
  "devour-for-power": "Mill and steal! Fill graveyards and play opponents' cards. Their deck is yours!",
  "wade-into-battle": "Giants and warriors! Big creatures clash aggressively. Might makes right!",
  "vehicle-squadron": "Vehicles attack! This deck features cars, ships, and machines. Start your engines!",
  "seize-control": "Steal everything! Take opponents' permanents. Playing their deck against them!",
  "swell-the-host": "Elf tokens swarm! Generate mana and overwhelm. A forest of creatures!",
  "sworn-to-darkness": "Demons deal dark power! Sacrifice for strength. Power at any cost!",
  "eternal-bargain": "Make deals with demons! Sacrifice for power and dominate. Every deal has a price!",
  "evasive-maneuvers": "Fly over defenses! Flying creatures and control. Rule the skies!",
  "mind-seize": "Control and steal! Take opponents' spells and creatures. Their power is yours!"
};
